language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - cd /home/travis/build/jmacgregor-accenture/travisRadiator/DotNetCore/TravisRadiator/
    - dotnet restore
    - dotnet build